FROM registry.access.redhat.com/ubi9/ubi:latest

COPY config.yml config.yml
COPY registry registry

VOLUME ["/var/lib/registry"]
EXPOSE 5000

ENTRYPOINT ["/registry"]
CMD ["serve", "config.yml"]
      
