FROM registry.access.redhat.com/ubi9/go-toolset:1.26 AS builder
COPY go.mod go.mod
COPY go.sum go.sum
COPY pkg/iso-builder/config/go.mod pkg/iso-builder/config/go.mod
RUN go mod download
COPY . .
RUN make build-iso-builder

FROM registry.access.redhat.com/ubi9/ubi-micro:9.7

COPY --from=builder build/openshift-iso-builder /openshift-iso-builder

LABEL summary="OpenShift ISO Builder" \
      name="openshift-iso-builder" \
      description="Builds OpenShift installation ISOs for disconnected environments" \
      io.k8s.description="Builds OpenShift installation ISOs for disconnected environments" \
      io.k8s.display-name="OpenShift ISO Builder" \
      com.redhat.component="openshift-iso-builder"
