FROM registry.access.redhat.com/ubi9/go-toolset:1.26.7-1790174511 AS builder
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
COPY . .
RUN cd cmd/iso-builder && CGO_ENABLED=0 GOFLAGS="" GO111MODULE=on go build -o /tmp/openshift-iso-builder

FROM registry.access.redhat.com/ubi9/ubi-micro:9.7

COPY --from=builder /tmp/openshift-iso-builder /openshift-iso-builder

LABEL summary="OpenShift ISO Builder" \
      name="openshift-iso-builder" \
      description="Builds OpenShift installation ISOs for disconnected environments" \
      io.k8s.description="Builds OpenShift installation ISOs for disconnected environments" \
      io.k8s.display-name="OpenShift ISO Builder" \
      com.redhat.component="openshift-iso-builder"
