package iso

import (
	"github.com/openshift/installer/pkg/asset"
	"github.com/sirupsen/logrus"
)

// RecoveryISO is an asset that generates the bootable ISO copied
// to a recovery partition in the OpenShift-based appliance.
type RecoveryISO struct {
	File *asset.File
}

var _ asset.WritableAsset = (*RecoveryISO)(nil)

// Dependencies returns the assets on which the Bootstrap asset depends.
func (a *RecoveryISO) Dependencies() []asset.Asset {
	return []asset.Asset{
		&BaseISO{},
	}
}

// Generate generates the image file for to ISO asset.
func (a *RecoveryISO) Generate(dependencies asset.Parents) error {
	logrus.Info("Generating recovery ISO...")

	return nil
}

// Name returns the human-friendly name of the asset.
func (a *RecoveryISO) Name() string {
	return "Appliance Recovery ISO"
}

// Load returns the ISO from disk.
func (a *RecoveryISO) Load(f asset.FileFetcher) (bool, error) {
	// The ISO will not be needed by another asset so load is noop.
	// This is implemented because it is required by WritableAsset
	return false, nil
}

// Files returns the files generated by the asset.
func (i *RecoveryISO) Files() []*asset.File {
	if i.File != nil {
		return []*asset.File{i.File}
	}
	return []*asset.File{}
}
