package registry

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/containers/image/pkg/sysregistriesv2"
	"github.com/openshift/installer/pkg/asset"
	installerTypes "github.com/openshift/installer/pkg/types"
	"github.com/pelletier/go-toml"
	"github.com/pkg/errors"

	"github.com/openshift/appliance/pkg/asset/config"
	"github.com/openshift/appliance/pkg/types"
)

var (
	registriesConfFilename = filepath.Join("mirror", "registries.conf")
)

// RegistriesConf generates the registries.conf file.
type RegistriesConf struct {
	File   *asset.File
	Config *sysregistriesv2.V2RegistriesConf
}

var _ asset.Asset = (*RegistriesConf)(nil)

// Name returns a human friendly name for the asset.
func (*RegistriesConf) Name() string {
	return "Mirror Registries Config"
}

// Dependencies returns all the dependencies directly needed to generate
// the asset.
func (*RegistriesConf) Dependencies() []asset.Asset {
	return []asset.Asset{
		&config.EnvConfig{},
	}
}

func (i *RegistriesConf) Generate(dependencies asset.Parents) error {
	envConfig := &config.EnvConfig{}
	dependencies.Get(envConfig)

	mirrorSources := GetDefaultOCPDigestMirrorSources()
	// TODO(MGMT-14412): Implement a logic to ensure additional image sources are served via local registry.
	// Merge applianceConfig.ImageDigestSources into mirrorSources
	tomlRegistries := types.ConvertToTOMLRegistries(mirrorSources)

	registriesData, err := toml.Marshal(tomlRegistries)
	if err != nil {
		return err
	}

	i.File = &asset.File{
		Filename: registriesConfFilename,
		Data:     registriesData,
	}

	return nil
}

func (i *RegistriesConf) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(registriesConfFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, errors.Wrap(err, fmt.Sprintf("failed to load %s file", registriesConfFilename))
	}

	registriesConf := &sysregistriesv2.V2RegistriesConf{}
	if err = toml.Unmarshal(file.Data, registriesConf); err != nil {
		return false, errors.Wrapf(err, "failed to unmarshal %s", registriesConfFilename)
	}

	i.File, i.Config = file, registriesConf

	return true, nil
}

// Files returns the files generated by the asset.
func (i *RegistriesConf) Files() []*asset.File {
	if i.File != nil {
		return []*asset.File{i.File}
	}
	return []*asset.File{}
}

func GetDefaultOCPDigestMirrorSources() []installerTypes.ImageDigestSource {
	return []installerTypes.ImageDigestSource{
		{
			Source: config.OcpReleaseSource,
			Mirrors: []string{
				fmt.Sprintf("%s:5000/openshift/release-images", config.RegistryDomain),
			},
		},
		{
			Source: config.OcpArtDevSource,
			Mirrors: []string{
				fmt.Sprintf("%s:5000/openshift/release-images", config.RegistryDomain),
			},
		},

		// TODO: remove once not using custom AGENT_DOCKER_IMAGE from quay.io
		{
			Source: "quay.io",
			Mirrors: []string{
				fmt.Sprintf("%s:5000", config.RegistryDomain),
			},
		},
	}
}
