// Code generated by MockGen. DO NOT EDIT.
// Source: release.go
//
// Generated by this command:
//
//	mockgen -source=release.go -package=release -destination=mock_release.go
//

// Package release is a generated GoMock package.
package release

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRelease is a mock of Release interface.
type MockRelease struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseMockRecorder
	isgomock struct{}
}

// MockReleaseMockRecorder is the mock recorder for MockRelease.
type MockReleaseMockRecorder struct {
	mock *MockRelease
}

// NewMockRelease creates a new mock instance.
func NewMockRelease(ctrl *gomock.Controller) *MockRelease {
	mock := &MockRelease{ctrl: ctrl}
	mock.recorder = &MockReleaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelease) EXPECT() *MockReleaseMockRecorder {
	return m.recorder
}

// ExtractCommand mocks base method.
func (m *MockRelease) ExtractCommand(command, dest string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractCommand", command, dest)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractCommand indicates an expected call of ExtractCommand.
func (mr *MockReleaseMockRecorder) ExtractCommand(command, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractCommand", reflect.TypeOf((*MockRelease)(nil).ExtractCommand), command, dest)
}

// ExtractFile mocks base method.
func (m *MockRelease) ExtractFile(image, filename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFile", image, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFile indicates an expected call of ExtractFile.
func (mr *MockReleaseMockRecorder) ExtractFile(image, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFile", reflect.TypeOf((*MockRelease)(nil).ExtractFile), image, filename)
}

// GetImageFromRelease mocks base method.
func (m *MockRelease) GetImageFromRelease(imageName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageFromRelease", imageName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageFromRelease indicates an expected call of GetImageFromRelease.
func (mr *MockReleaseMockRecorder) GetImageFromRelease(imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageFromRelease", reflect.TypeOf((*MockRelease)(nil).GetImageFromRelease), imageName)
}

// MirrorInstallImages mocks base method.
func (m *MockRelease) MirrorInstallImages() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MirrorInstallImages")
	ret0, _ := ret[0].(error)
	return ret0
}

// MirrorInstallImages indicates an expected call of MirrorInstallImages.
func (mr *MockReleaseMockRecorder) MirrorInstallImages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MirrorInstallImages", reflect.TypeOf((*MockRelease)(nil).MirrorInstallImages))
}

// GetMappingFile mocks base method.
func (m *MockRelease) GetMappingFile() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappingFile")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappingFile indicates an expected call of GetMappingFile.
func (mr *MockReleaseMockRecorder) GetMappingFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappingFile", reflect.TypeOf((*MockRelease)(nil).GetMappingFile))
}
