package diskimage

import (
	"github.com/openshift/installer/pkg/asset"
	"github.com/sirupsen/logrus"
)

// BaseDiskImage is an asset that generates the base disk image (RHCOS) of OpenShift-based appliance.
type BaseDiskImage struct {
	File *asset.File
}

var _ asset.WritableAsset = (*BaseDiskImage)(nil)

// Dependencies returns the assets on which the Bootstrap asset depends.
func (a *BaseDiskImage) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Generate generates the image file for to ISO asset.
func (a *BaseDiskImage) Generate(dependencies asset.Parents) error {
	logrus.Info("Downloading appliance base disk image...")

	return nil
}

// Name returns the human-friendly name of the asset.
func (a *BaseDiskImage) Name() string {
	return "Base disk image (RHCOS)"
}

// Load returns the ISO from disk.
func (a *BaseDiskImage) Load(f asset.FileFetcher) (bool, error) {
	// The ISO will not be needed by another asset so load is noop.
	// This is implemented because it is required by WritableAsset
	return false, nil
}

// Files returns the files generated by the asset.
func (i *BaseDiskImage) Files() []*asset.File {
	if i.File != nil {
		return []*asset.File{i.File}
	}
	return []*asset.File{}
}
